/* autogenerated by Processing revision 1313 on 2026-04-12 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import oscP5.*;
import netP5.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class WeAreU_gameVisualizer extends PApplet {

// ============================================================
// Main.pde  –  Haupt-Tab
// Nur Setup, Draw, HUD und OSC-Handler. Keine Spiellogik hier.
// ============================================================




OscP5 oscP5;
PGraphics canvas;

// Spielzustand
int state = 0; // nur Initialisierung in setup() wird state zugewiesen

// Spielobjekte
Player p1, p2;
ArrayList<GameObject> gameObjects = new ArrayList<GameObject>();

// Stats
int timeLeft;

// Konstante Spielfeldgröße (Senderseite)
final float GAME_SIZE = 600.0f;

// Größen (skaliert für Viewport)
float playerSize, coinSize;

public void settings(){
  size(WINDOW_W, WINDOW_H);
}

public void setup() {
  canvas = createGraphics(VIEWPORT_W, VIEWPORT_H);

  state = STATE_MENU;
  oscP5 = new OscP5(this, OSC_PORT);

  playerSize = PLAYER_SIZE * (VIEWPORT_W / GAME_SIZE);
  coinSize   = COIN_SIZE * (VIEWPORT_W / GAME_SIZE);

  // Spieler anlegen – Farbe und ID übergeben
  p1 = new Player("p1", color(COL_P1));
  p2 = new Player("p2", color(COL_P2));

  // Coin als erstes GameObject anlegen
  gameObjects.add(new GameObject("coin", color(COL_COIN)));
}


public void draw() {
  background(color(COL_BG));

  // draw on canvas
  canvas.beginDraw();
  canvas.background(color(COL_BG));
  canvas.rectMode(CENTER);
  canvas.ellipseMode(CENTER);

  // GAME STATES
  if(state == STATE_MENU){
    drawReceiverMenu(canvas);
  }
  else if(state == STATE_PLAYING){
    drawReceiverGame(canvas);
  }
  else if(state == STATE_GAMEOVER){
    drawReceiverGameOver(canvas);
  }

  canvas.endDraw();

  // show canvas on split screen
  image(canvas, 0, 0);
  image(canvas, VIEWPORT_W, 0);
}


// --- OSC-EVENT HANDLER ---
public void oscEvent(OscMessage msg) {
  String addr = msg.addrPattern();

  if (addr.equals("/p1/pos")) {
    p1.x = msg.get(0).floatValue();
    p1.y = msg.get(1).floatValue();
  }
  else if (addr.equals("/p2/pos")) {
    p2.x = msg.get(0).floatValue();
    p2.y = msg.get(1).floatValue();
  }
  else if (addr.equals("/coin/pos")) {
    // Coin ist immer das erste GameObject in der Liste
    gameObjects.get(0).x = msg.get(0).floatValue();
    gameObjects.get(0).y = msg.get(1).floatValue();
  }
  else if (addr.equals("/game/stats")) {
    state    = msg.get(0).intValue();
    timeLeft = msg.get(1).intValue();
    p1.score = msg.get(2).intValue();
    p2.score = msg.get(3).intValue();
  }

  // Neue OSC-Adressen einfach hier unten anfügen:
  // else if (addr.equals("/powerup/pos")) { ... }
}


// --- DRAW STATES ---

public void drawReceiverMenu(PGraphics pg) {
  pg.textAlign(CENTER, CENTER);
  pg.fill(255);
  pg.textSize(26);
  pg.text("Warte auf Spieler...", pg.width/2, pg.height/2);
}

public void drawReceiverGame(PGraphics pg) {
  pg.noStroke();

  // Alle GameObjects zeichnen (Coin, PowerUps, etc.)
  for (GameObject obj : gameObjects) {
    obj.draw(pg, coinSize);
  }

  // Spieler zeichnen
  p1.draw(pg, playerSize);
  p2.draw(pg, playerSize);

  // UI
  drawHUD(pg);
}

public void drawReceiverGameOver(PGraphics pg) {
  pg.textAlign(CENTER, CENTER);

  pg.fill(255);
  pg.textSize(32);
  pg.text("GAME OVER", pg.width/2, pg.height/2 - 60);

  String resultText;
  if (p1.score > p2.score) {
    pg.fill(p1.col);
    resultText = "SPIELER 1 GEWINNT!";
  } else if (p2.score > p1.score) {
    pg.fill(p2.col);
    resultText = "SPIELER 2 GEWINNT!";
  } else {
    pg.fill(200);
    resultText = "UNENTSCHIEDEN!";
  }

  pg.textSize(26);
  pg.text(resultText, pg.width/2, pg.height/2 - 10);

  pg.textSize(22);
  pg.fill(p1.col);
  pg.textAlign(RIGHT);
  pg.text("P1: " + p1.score, pg.width/2 - 20, pg.height/2 + 40);

  pg.fill(p2.col);
  pg.textAlign(LEFT);
  pg.text("P2: " + p2.score, pg.width/2 + 20, pg.height/2 + 40);
}

public void drawHUD(PGraphics pg) {
  pg.fill(255);
  pg.textSize(18);
  pg.textAlign(CENTER);
  pg.text(timeLeft, pg.width/2, 30);

  pg.fill(p1.col);
  pg.textSize(25);
  pg.textAlign(LEFT);
  pg.text(p1.score, 20, 30);

  pg.fill(p2.col);
  pg.textAlign(RIGHT);
  pg.text(p2.score, pg.width - 20, 30);
}
// ============================================================
// Config.pde  –  Alle anpassbaren Spielparameter
// Hier ändern, nie tief im Code suchen müssen.
// ============================================================

// --- Fenster & Viewport ---
final int   WINDOW_W     = 800;
final int   WINDOW_H     = 480;
final int   VIEWPORT_W   = 400;
final int   VIEWPORT_H   = 480;

// --- Netzwerk ---
final int   OSC_PORT     = 12001;

// --- Spielfeld ---
// GAME_SIZE bleibt in [MAIN].pde, da Global sein muss und gx()/gy() in Utils.pde davon abhängen

// --- Objektgrössen (auf Senderseite, werden automatisch skaliert) ---
final float PLAYER_SIZE  = 60.0f;
final float COIN_SIZE    = 40.0f;
final float POWERUP_SIZE = 35.0f;

// --- Farben ---
final int COL_P1       = 0xFF3296FF;  // Blau
final int COL_P2       = 0xFFFF3232;  // Rot
final int COL_COIN     = 0xFFFFFF00;  // Gelb
final int COL_BG       = 0xFF141414;  // Hintergrund
// ============================================================
// GameObject.pde  –  Tab für alle Spielobjekte
// Coin, PowerUp, Obstacle – alles erbt von hier.
// ============================================================

class GameObject {
  String type;
  int col;
  float x, y;
  boolean active = true;

  GameObject(String type, int col) {
    this.type = type;
    this.col  = col;
  }

  // Basis-Draw: Rechteck (kann in Subklassen überschrieben werden)
  public void draw(PGraphics pg, float size) {
    if (!active) return;
    pg.fill(col);
    pg.rect(gx(x, pg), gy(y, pg), size, size);
  }
}


// --- Subklassen für spezifische Objekte ---

// Beispiel: PowerUp (Dreieck statt Rechteck)
class PowerUp extends GameObject {
  PowerUp() {
    super("powerup", color(0, 255, 100));
  }

  @Override public 
  void draw(PGraphics pg, float size) {
    if (!active) return;
    pg.fill(col);
    float cx = gx(x, pg);
    float cy = gy(y, pg);
    pg.triangle(
      cx,           cy - size/2,
      cx - size/2,  cy + size/2,
      cx + size/2,  cy + size/2
    );
  }
}

// Beispiel: Hindernis (größeres graues Rechteck)
class Obstacle extends GameObject {
  Obstacle() {
    super("obstacle", color(150));
  }

  @Override public 
  void draw(PGraphics pg, float size) {
    if (!active) return;
    pg.fill(col);
    pg.rect(gx(x, pg), gy(y, pg), size * 2, size); // breiter als hoch
  }
}
// ============================================================
// Player.pde  –  Tab für die Spieler-Klasse
// ============================================================

class Player {
  String id;
  int col;
  float x, y;
  int score;

  Player(String id, int col) {
    this.id  = id;
    this.col = col;
  }

  public void draw(PGraphics pg, float size) {
    pg.fill(col);
    pg.ellipse(
      gx(x, pg),
      gy(y, pg),
      size, size
    );
  }
}
// ============================================================
// Utils.pde  –  Tab für globale Hilfsfunktionen & Konstanten
// ============================================================

// --- State-Konstanten ---
final int STATE_MENU     = 0;
final int STATE_PLAYING  = 1;
final int STATE_GAMEOVER = 2;
// Neue States einfach hier hinzufügen:
// final int STATE_PAUSE = 3;


// --- Koordinaten-Mapping ---
// Rechnet Spielfeld-Koordinaten (0–GAME_SIZE) in Viewport-Koordinaten um.
// GAME_SIZE kommt aus Main.pde und ist dort als global deklariert.

public float gx(float x, PGraphics pg) {
  return map(x, 0, GAME_SIZE, 0, pg.width);
}

public float gy(float y, PGraphics pg) {
  return map(y, 0, GAME_SIZE, 0, pg.height);
}


  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "--full-screen", "--bgcolor=#666666", "--hide-stop", "WeAreU_gameVisualizer" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
